// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYZUYEMA0wHyConK_3iSErjuE-Eucm3Zg',
    appId: '1:379541079424:web:fa66729efb0898ef142d65',
    messagingSenderId: '379541079424',
    projectId: 'greenmessages-63ca7',
    authDomain: 'greenmessages-63ca7.firebaseapp.com',
    databaseURL: 'https://greenmessages-63ca7-default-rtdb.firebaseio.com',
    storageBucket: 'greenmessages-63ca7.firebasestorage.app',
    measurementId: 'G-W9MC2PX697',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgZ9Y5bqjXX2zMoWaTBjLSj1tEo0YEExw',
    appId: '1:379541079424:ios:e36786569a3c5c9d142d65',
    messagingSenderId: '379541079424',
    projectId: 'greenmessages-63ca7',
    databaseURL: 'https://greenmessages-63ca7-default-rtdb.firebaseio.com',
    storageBucket: 'greenmessages-63ca7.firebasestorage.app',
    iosBundleId: 'com.example.greenMessageApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYZUYEMA0wHyConK_3iSErjuE-Eucm3Zg',
    appId: '1:379541079424:web:10c56f90281e2476142d65',
    messagingSenderId: '379541079424',
    projectId: 'greenmessages-63ca7',
    authDomain: 'greenmessages-63ca7.firebaseapp.com',
    databaseURL: 'https://greenmessages-63ca7-default-rtdb.firebaseio.com',
    storageBucket: 'greenmessages-63ca7.firebasestorage.app',
    measurementId: 'G-LN1T97EKFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWgsiZmDHlwh5zjAkJvzKlaNtmq66WLJo',
    appId: '1:379541079424:android:edc8c08cbeb6f6a1142d65',
    messagingSenderId: '379541079424',
    projectId: 'greenmessages-63ca7',
    databaseURL: 'https://greenmessages-63ca7-default-rtdb.firebaseio.com',
    storageBucket: 'greenmessages-63ca7.firebasestorage.app',
  );

}